name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGE_TOKEN }}

    - name: 'Build Inventory Image'
      run: |
        docker build . --tag ghcr.io/${{ github.actor }}/verve-unique-request-assignment:latest
        docker push ghcr.io/${{ github.actor }}/verve-unique-request-assignment:latest

